apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redirect-operator
  namespace: redirect-operator
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
